stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py data/raw/ data/interim/ data/processed/
    deps:
    - data/raw/
    outs:
    - data/interim/:
        persist: true
  add_features:
    cmd: python src/features/build_features.py data/interim/ data/processed/
    deps:
    - data/interim/
    outs:
    - data/processed/:
        persist: true

  train:
    cmd: python src/models/train_model.py data/processed/train_data.pkl data/processed/train_target.pkl
      models/
    deps:
    - data/processed/
    outs:
    - models/:
        persist: true
  evaluate:
    cmd: python src/models/evaluate.py models/
    deps:
    - models/
