stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py data/raw/ data/interim/
    deps:
    - data/raw/
    outs:
    - data/interim/:
        persist: true
  add_features:
    cmd: python src/features/build_features.py data/interim/ data/processed/
    deps:
    - data/interim/
    outs:
    - data/processed/:
        persist: true
